### ISSUE TITLE
BAM parsing

### ISSUE THREAD

**Issue by alpapan** [mfiers/hagfish#1]
Hello Mark

After Ross showed some excellent graphs, I've been trying to trial your software. I'm having problems parsing the BAM files from the Kanga aligner; it has the following header:
@SQ AS:genome   SN:scaffold_0   LN:5118119

but sadly hagfish_extract uses an array to determine sequence length rather than doing a regex match for LN:\d+. could we please fix it (sorry I'm not a python person qualified submit a patch)

many thanks
alexie

**Comment by mfiers** [comment]
Hi Alexie. 

Thanks for the request - and identifying what the problem is :) - you make my life easy. A Regex is a nicer solution.

Fixed the code & the new version is on github.

(btw - I don't think that the lower case @sq is conform BAM format - but hagfish does accept that now as well)

Cheers
Mark

(@RCrowhurst)

**Comment by alpapan** [comment]
oops,  i did get your email (replied to Ross).

@sq was a typo from my part

On 17 April 2012 13:07, Mark Fiers
reply@reply.github.com
wrote:

**Comment by mfiers** [comment]
Does it work for you now? I'd be keen to hear about your experiences.

**Comment by alpapan** [comment]
Hi Mark

Sorry for the late reply. I realized I had to make another assembly
tweak before using hagfish again.

I'm running the alignments again but I need some help interpreting the
graphs (colours, the concept of inclusive/exclusive etc). is it
possible to write some more on the wiki?

On another note, I have a linkage map which i use to determine which
scaffolds are misassembled. i was wondering, how difficult would it be
to provide hagfish with a TAB delimited text file of positions (id,
position, colour) that I would get a 'coloured marker' to appear? I
can think of other applications (e.g. gene clusters) for this
generally but only if it is easy to implement...

alternatively, having hagfish output a wig file would be equally
useful (can visualize on IGV)

thank you
a

On 20 April 2012 09:03, Mark Fiers
reply@reply.github.com
wrote:

**Comment by mfiers** [comment]
Hi Alexie - Uncertain why - but it seems that github does not notify me of new messages - so - sorry for my late reply. I am working on improving the wiki with information on the plots - I'll notify you once I have the cplot2 & blockplot properly explained. 
The markers & wig file are both good suggestions - let me get back to you on that. 

(opened a few issues)
