### ISSUE TITLE
Demo test suite in repository

### ISSUE THREAD

**Issue by alpapan** [mfiers/hagfish#5]
Dear Mark
Is it possible to have a small demo/test in the repo? I'd like to show your program to my engineer and as he is not a bioinformatician he would need some basic demo. I'm thinking of asking him to create a JS application maybe using jbrowse or a new framework using a standard library but first we need to scope it.

I'm happy to provide that if you want (but might be easier if you did) and one can even use it for unit testing?

it wouldn't need to be more than say 100 reads and say 500 bp...

thanks
a

**Comment by alpapan** [comment]
p.s. I meant JS for the graphing/exploring capability not the parsing the data

**Comment by alpapan** [comment]
p.s. I meant JS for the graphing/exploring capability not the parsing the data

**Comment by mfiers** [comment]
Ok - I can do that.

**Comment by mfiers** [comment]
Finally' In the demo_data directory.
I needed to find a set that has a few interesting features. These data sets will also serve for generating plots in the documentation - it is not exactly a very small dataset - but you can extract whatever you need.

@alpapan @RCrowhurst

**Comment by alpapan** [comment]
should we have a cmd that does the unit testing...?

**Comment by mfiers** [comment]
Hi Alexie 

Moved to ./test subdirectory & added a run_test.sh script that does a simple hagfish run.

@RCrowhurst
