### ISSUE TITLE
support sam for hagfish_extract

### ISSUE THREAD

**Issue by alpapan** [mfiers/hagfish#6]
Hello

Reading the BAM file is great but some times we don't want to have the overhead of creating a bam if the file is not stored. Can we allow for SAM files (by adding the -S option in the two samtools view commands?)?
Easiest is for user to specify it is a SAM with --sam

thank you
a

**Comment by mfiers** [comment]
Done - 

added a -S flag to hagfish_extract

cheers
M

@RCrowhurst
