### ISSUE TITLE
library specific

### ISSUE THREAD

**Issue by alpapan** [mfiers/hagfish#7]
Hello

Another small feature request:

the option to use a specified library (bam file) so that e.g.
-library 1_2_vs_contigs_sopra.fasta.sam.fix

this is used
coverage/1_2_vs_contigs_sopra.fasta.sam.fix/scaffold_20.coverage.r_ok_ends.gz
instead of 
combined/scaffold_20_20.coverage.r_ok_ends.gz

(should be straightforward to implement, no?). 

once we have that, i can make hagfish or wiggle graphs and see how each library behaves (e.g compare 20kb with 3kb)...

For extra points (but extra time) then multiple libraries can be given, reading each file it turn (or also the wildcard 'all'), negating thus the need to run hagfish_combine....?

thanks
alexie

**Comment by mfiers** [comment]
This does take a little more time to properly implement. But a few scripts do have the possibility now to select one or more  libraries using the -l parameter. Most notable is hagfish_cplot2.
