### ISSUE TITLE
Can't plot with hagfish_cplot2

### ISSUE THREAD

**Issue by philippbayer** [mfiers/hagfish#8]
Hello, 

thanks for the tip on this package on Biostar!

I've spent the last couple of days playing around with test-data and I can't get the library to plot, I ran hagfish-extract/hagfish_gapfinder/hagfish_coverage_combine and then hagfish_cplot2:

``` python
python hagfish_cplot2 -n 5e3 --ymax 200 chrom3_v3
```

where chrom3 is my chromosome I aligned reads to (for comparison I used bowtie with the parameters from the wiki).

I get the following error (same when I don't give any parameters):

``` python
Traceback (most recent call last):
  File "hagfish_cplot2", line 159, in <module>
    plot.save(tag='cplot2')
  File "/HPC/home/s4279812/work/TestingHagfish/hagfish/hagfishUtils.py", line 426, in save
    bbox_inches='tight')
  File "/bio1/opt/python/lib/python2.7/site-packages/matplotlib-1.0.0-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 363, in savefig
    return fig.savefig(*args, **kwargs)
  File "/bio1/opt/python/lib/python2.7/site-packages/matplotlib-1.0.0-py2.7-linux-x86_64.egg/matplotlib/figure.py", line 1084, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/bio1/opt/python/lib/python2.7/site-packages/matplotlib-1.0.0-py2.7-linux-x86_64.egg/matplotlib/backend_bases.py", line 1852, in print_figure
    **kwargs)
  File "/bio1/opt/python/lib/python2.7/site-packages/matplotlib-1.0.0-py2.7-linux-x86_64.egg/matplotlib/backends/backend_agg.py", line 438, in print_png
    FigureCanvasAgg.draw(self)
  File "/bio1/opt/python/lib/python2.7/site-packages/matplotlib-1.0.0-py2.7-linux-x86_64.egg/matplotlib/backends/backend_agg.py", line 393, in draw
    self.renderer = self.get_renderer()
  File "/bio1/opt/python/lib/python2.7/site-packages/matplotlib-1.0.0-py2.7-linux-x86_64.egg/matplotlib/backends/backend_agg.py", line 404, in get_renderer
    self.renderer = RendererAgg(w, h, self.figure.dpi)
  File "/bio1/opt/python/lib/python2.7/site-packages/matplotlib-1.0.0-py2.7-linux-x86_64.egg/matplotlib/backends/backend_agg.py", line 59, in __init__
    self._renderer = _RendererAgg(int(width), int(height), dpi, debug=False)
ValueError: width and height must each be below 32768
```

I've tried playing around with the -W and -H parameters but no dice, do you have any idea?

**Comment by mfiers** [comment]
No - this is new to me. 
One observation - you seem to be using matplotlib 1.0.0 - any chance of upgrading to 1.1.0? 
If that does not work - could you rerun with -vv and see if that gives you any information?

M

**Comment by philippbayer** [comment]
I can't update matplotlib on the current server (I'm not admin) but I'll put in a ticket and try to update it on my own machine.

I'm currently re-running with -vv and see something like this output:

``` python
plot DEBUG  start plotting band 581 (corr -582000)
band.581 DEBUG  Start plotting
main INFO   2905000 2909999
band.582 DEBUG  printing from 2910000 to 2914999
band.582 DEBUG  preprocessing band data
band.582 DEBUG  defining band from -582500.0 to -583500.0
plot DEBUG  start plotting band 582 (corr -583000)
```

I guess these negative numbers shouldn't be?

On the plus side, I managed to get something plotted by using  -s 0 and -e 1e4 parameters, but the plot then looks extremely weird: https://imgur.com/YeRGQ  

Any ideas?

Thanks for the help!!

Edit:

Here's the -vv output when I use -s 0 and -e 1e4:

``` python
main INFO   starting hagfish_cplot2
Tap_XA05_v3
data INFO   Loading sequence: Tap_XA05_v3
data INFO   Loading combined library
        data INFO   Cannot find gap data
data DEBUG  loaded coverage plots of len 15652766
data INFO   stats: median ok is 0.0 (h 0.0)
data INFO   stats: average ok is 0.0119660001306
data INFO   stats: min, max ok is 0, 195
plot INFO   plot stops at 10000
plot INFO   Ploting 5000 nucleotides per band
plot INFO   Plotting from 0 to 10000 (10000 nt)
plot INFO   Plotting 2 bands
plot INFO   setting ymax (--ymax) to 1000
plot DEBUG  no bands: 2 
plot DEBUG  top/bottom margin: 0.066667 (0.5 / 4.000000 ) 
plot DEBUG  creating axes with coords lbrt 0.0800 0.0667 0.8500 0.8667 
band.000 DEBUG  printing from 0 to 4999
band.000 DEBUG  preprocessing band data
band.000 DEBUG  defining band from -500.0 to -1500.0
plot DEBUG  start plotting band 0 (corr -1000)
band.000 DEBUG  Start plotting
main INFO   0 4999
band.001 DEBUG  printing from 5000 to 9999
band.001 DEBUG  preprocessing band data
band.001 DEBUG  defining band from -1500.0 to -2500.0
plot DEBUG  start plotting band 1 (corr -2000)
band.001 DEBUG  Start plotting
main INFO   5000 9999
plot INFO   writing to Tap_XA05_v3_0_10000_cplot2.png
```

Looks better than above, but again negative values (and the strange picture I already attached).

**Comment by mfiers** [comment]
<edit - that was too quick>

the numbers are a little confusing - these are not coordinates in nt space.

the distribution comes with a test test (in `./test`) - could you try to run the test sets - to see if it is your data or my code :)

(cd test; bash test.sh)

**Comment by philippbayer** [comment]
Same results, here's with -s omitted:

``` python
data INFO   Loading sequence: Tap_XA05_v3
data INFO   Loading combined library
data INFO   Cannot find gap data
data DEBUG  loaded coverage plots of len 15652766
data INFO   stats: median ok is 0.0 (h 0.0)
data INFO   stats: average ok is 0.0119660001306
data INFO   stats: min, max ok is 0, 195
plot INFO   plot stops at 10000
plot DEBUG  nt per band is not specified
plot INFO   Ploting 10000 nucleotides per band
plot INFO   Plotting from 0 to 10000 (10000 nt)
plot INFO   Plotting 1 bands
plot INFO   setting ymax (--ymax) to 600
plot DEBUG  no bands: 1 
plot DEBUG  top/bottom margin: 0.111111 (0.5 / 2.000000 ) 
plot DEBUG  creating axes with coords lbrt 0.0800 0.1111 0.8500 0.7778 
band.000 DEBUG  printing from 0 to 9999
band.000 DEBUG  preprocessing band data
band.000 DEBUG  defining band from -300.0 to -900.0
plot DEBUG  start plotting band 0 (corr -600)
band.000 DEBUG  Start plotting
main INFO   0 9999
plot INFO   writing to Tap_XA05_v3_0_10000_cplot2.png
```

The plot looks identical to the last one.

**Comment by mfiers** [comment]
Oh - I just now notice that you're creating a humongous figure - 
that's likely the problem. Please switch to a much larger -n (try 1e6 or so) value for cplot2 or use hagfish_blockplot (also with a large -n)

**Comment by mfiers** [comment]
And - I should read your comments better - sorry about that

The image looks a little strange - I do agree. I'd retry that image with something like  `-e 1e6 -n 5e5` - and scale up from there...

**Comment by philippbayer** [comment]
I'm playing currently around and re-started with another bam-alignment - is it normal that when I run hagfish_extract -vv,
a lot of 

``` python
HAGFISH WARNING dist 1012  peakhigh 534 : 4
HAGFISH WARNING dist 547  peakhigh 534 : 0
HAGFISH WARNING dist 719  peakhigh 534 : 1
```

pop up?

**Comment by mfiers** [comment]
Yes - a remnant of the debugging process - I've just removed them.

On Wed, Jun 20, 2012 at 5:41 PM, drsnuggles
reply@reply.github.com
wrote:

**Comment by philippbayer** [comment]
Fixed it! Turns out, something in the original bam-file was broken/weird (no clue what?), by restarting the whole analysis with another chromosome I get a graph similar to the one in the wiki. 

Thanks for all the help! As soon as I got the heatmaps figured out I'll put some more information in the wiki.

**Comment by mfiers** [comment]
Great! Good to hear, glad it works.

I'd be very grateful if you'd find some time to improve the wiki.

cheers
Mark

On Thu, Jun 21, 2012 at 11:33 AM, drsnuggles
reply@reply.github.com
wrote:
