### ISSUE TITLE
samtools view -f 67 doesn't like SOAPaligner-output converted to bam

### ISSUE THREAD

**Issue by philippbayer** [mfiers/hagfish#9]
Hi again,

my workgroup prefers to work with SOAPaligner and there's a tiny bug in Hagfish related to that:

When I convert SOAP-output to SAM via soap2sam.pl and get the header using 

```
samtools view -bt bla.fai output.sam > output.bam 
```

hagfish_extract doesn't work - because

```
samtools view -f 67 
```

in hagfish_extract filters for the "paired"-tag that, for some reason, isn't inserted by samtools, so hagfish_extract has 0 lines to work on.  Removing the "-f 67" part works perfectly (I get nice plots at least) because SOAP has three types of output files (paired reads, unpaired reads and unmapped) so it's already ensured that all reads in the bam-file are paired.

Maybe some extra-flag like "output is converted SOAP" is needed, so hagfish-extract runs samtools view without "-f 67"?

**Comment by mfiers** [comment]
Added a flag (default  67) for hagfish_extract:

```
--samFlag=SAMFLAG  -f flag value to use with samtools - defaults to 67 to
                   get only the properly mapped, forward reads. Note that
                   removing this flag - hagfish might count each read twice
                   (once forward, once reverse)
```

Beware that if you do not select for forward reads - it is possible that both forward & reverse reads are being counted - effectively doubling the observed coverage.
